name: Build PyTorch with CUDA 11.8

on:
  workflow_dispatch:
    inputs:
      pytorch_version:
        description: 'PyTorch version to build (e.g. 2.0.0, 2.1.0)'
        required: true
        type: string
      python_version:
        description: 'Python version to build for'
        required: true
        default: '3.10'
        type: choice
        options:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 6
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup directories
        run: |
          mkdir -p _build/artifacts

      - name: Set environment variables
        run: |
          echo "PYTORCH_VERSION=${{ github.event.inputs.pytorch_version }}" >> $GITHUB_ENV
          echo "CUDA_VERSION=11.8" >> $GITHUB_ENV
          echo "CUDA_VERSION_NO_DOT=118" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ github.event.inputs.python_version }}" >> $GITHUB_ENV

      - name: Create Dockerfile
        run: |
          cat > Dockerfile.cuda118 << 'EOL'
          FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

          # Accept Python version as build argument
          ARG PYTHON_VERSION

          # Set environment variables to avoid interactive prompts
          ENV DEBIAN_FRONTEND=noninteractive

          # Install dependencies 
          RUN apt-get update && apt-get install -y --no-install-recommends \
              build-essential \
              ca-certificates \
              cmake \
              curl \
              git \
              libjpeg-dev \
              libpng-dev \
              libopenblas-dev \
              ninja-build \
              software-properties-common \
              wget \
              && rm -rf /var/lib/apt/lists/*

          # Install Python from deadsnakes PPA
          RUN apt-get update && \
              apt-get install -y software-properties-common && \
              add-apt-repository ppa:deadsnakes/ppa && \
              apt-get update && \
              apt-get install -y --no-install-recommends \
              python${PYTHON_VERSION} \
              python${PYTHON_VERSION}-dev \
              python${PYTHON_VERSION}-distutils \
              && rm -rf /var/lib/apt/lists/*

          # Create symlinks for Python
          RUN ln -sf /usr/bin/python${PYTHON_VERSION} /usr/bin/python3 && \
              ln -sf /usr/bin/python3 /usr/bin/python

          # Install pip for the specific Python version
          RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python

          # Install dependencies for PyTorch
          RUN pip install wheel setuptools && \
              pip install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions

          # Set environment variables for build
          ENV USE_CUDA=1 \
              USE_CUDNN=1 \
              USE_MKLDNN=1 \
              BUILD_TEST=0 \
              USE_FBGEMM=1 \
              BUILD_SPLIT_CUDA=ON \
              CMAKE_POLICY_VERSION_MINIMUM=3.5

          WORKDIR /workspace
          EOL

      - name: Create build script
        run: |
          cat > build_pytorch.sh << 'EOL'
          #!/usr/bin/env bash
          set -exo pipefail

          # Setup git configuration
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # Check CMake version
          cmake --version

          # Clone PyTorch
          echo "Cloning PyTorch version ${PYTORCH_VERSION}"
          git clone -b "v${PYTORCH_VERSION}" --recursive https://github.com/pytorch/pytorch.git /workspace/pytorch
          cd /workspace/pytorch

          # Configure build environment
          export PYTORCH_BUILD_VERSION="${PYTORCH_VERSION}+cu${CUDA_VERSION_NO_DOT}"
          export PYTORCH_BUILD_NUMBER=1
          export TZ=UTC
          export TORCH_CUDA_ARCH_LIST="3.5;3.7"
          export CMAKE_POLICY_VERSION_MINIMUM=3.5
          
          # Memory optimization
          export MAX_JOBS=2
          
          # For CUDA 11.x builds
          export BUILD_SPLIT_CUDA=ON
          
          # Build PyTorch
          echo "Building PyTorch ${PYTORCH_VERSION} with CUDA ${CUDA_VERSION}"
          python setup.py bdist_wheel
          
          # Copy wheel file to shared directory
          cp dist/*.whl /artifacts/
          EOL
          
          chmod +x build_pytorch.sh

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PYTHON_VERSION=${{ github.event.inputs.python_version }} \
            -t pytorch-cuda118-builder \
            -f Dockerfile.cuda118 .

      - name: Build PyTorch
        run: |
          docker run --rm \
            -e PYTORCH_VERSION=${{ env.PYTORCH_VERSION }} \
            -e CUDA_VERSION=${{ env.CUDA_VERSION }} \
            -e CUDA_VERSION_NO_DOT=${{ env.CUDA_VERSION_NO_DOT }} \
            -v $(pwd)/_build/artifacts:/artifacts \
            -v $(pwd)/build_pytorch.sh:/workspace/build_pytorch.sh \
            pytorch-cuda118-builder \
            bash /workspace/build_pytorch.sh

      - name: List artifacts
        run: |
          ls -la _build/artifacts/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pytorch-${{ github.event.inputs.pytorch_version }}-cuda118
          name: PyTorch ${{ github.event.inputs.pytorch_version }} with CUDA 11.8
          body: |
            PyTorch ${{ github.event.inputs.pytorch_version }} with CUDA 11.8 support
            Built with architecture support for SM35, SM37, and newer architectures.
          draft: false
          prerelease: false
          files: _build/artifacts/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
